[build]
builder = "nixpacks"

[deploy]
startCommand = "gunicorn -w 4 -b :$PORT app:app"

[build.environment]
PYTHON_VERSION = "3.12"

[build.nixpacks]
provider = "python"
installCommand = "pip install -r requirements.txt"
startCommand = "gunicorn -w 4 -b :$PORT app:app"
